name: Deploy Angular App

on:
 push:
  branches:
    - config-frontend-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout do código
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 18

     - name: Install dependencies
       run: npm ci

     - name: Install Angular CLI
       run: npm install -g @angular/cli

     - name: Build of the Angular App
       run: |
       cd frontend
       npm install
       ng build --configuration=production
     - name: Deploy for Render
       env:
         RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
       run: |
         curl -X POST "https://api.render.com/deploy/srv-cvard3dsvqrc73c1f990key=${{ secrets.RENDER_API_KEY }}"
